name: Flight Monitor Automático

on:
  # Ejecutar según un schedule (cada 2 horas)
  schedule:
    - cron: '0 */2 * * *'  # A las horas 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22
  
  # Permitir ejecución manual desde la UI de GitHub
  workflow_dispatch:
    inputs:
      routes_count:
        description: 'Número de rutas a monitorear (máximo 4)'
        required: false
        default: '4'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar monitoreo
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
        AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
      run: |
        echo "🚀 Iniciando monitoreo de vuelos..."
        python monitor_script.py
    
    - name: Resumen
      if: success()
      run: |
        echo "✅ Monitoreo completado exitosamente"
        echo "📊 Los datos se guardaron en PostgreSQL"
        echo "🌐 Revisa el dashboard en Streamlit Cloud"
    
    - name: Notificar errores
      if: failure()
      run: |
        echo "❌ El monitoreo falló"
        echo "Revisa los logs para más detalles"
