# Configuración de credenciales para Streamlit
# Crea este archivo en la ruta: .streamlit/secrets.toml
# NO SUBAS ESTE ARCHIVO A GITHUB - debe estar en .gitignore

# Database Configuration (Render PostgreSQL)
DB_HOST = "dpg-d3g6g1p5pdvs73e8c0rg-a.oregon-postgres.render.com"
DB_PORT = 5432
DB_NAME = "vuelos_9lrw"
DB_USER = "vuelos"
DB_PASSWORD = "FOa7NtnssHMgheHCMilCRXYmLYQn7pko"

# Amadeus API Configuration
AMADEUS_API_KEY = "KAomv16lpjbjJFAmj42OgXtzEOzCHHlx"
AMADEUS_API_SECRET = "mwHaoM1gEV9bweN2"
